apiVersion: apps/v1
kind: Deployment
metadata:
  name: galasa-ecosystem-operator
  namespace: jdavies47
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: galasa-ecosystem-operator
      app.kubernetes.io/component: ecosystem
      app.kubernetes.io/instance: default
      app.kubernetes.io/part-of: galasa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: galasa-ecosystem-operator
        app.kubernetes.io/component: ecosystem
        app.kubernetes.io/instance: default
        app.kubernetes.io/version: "v2alpha1"
        app.kubernetes.io/part-of: galasa
        app: galasa-ecosystem-operator
        version: "v2alpha1"
    spec:
      serviceAccountName: galasa-ecosystem-operator
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: galasa-ecosystem-operator
        image: ko://github.com/galasa-dev/galasa-kubernetes-operator/cmd/operator
        args:
          - "-namespace"
          - "jdavies47"
        env:
        - name: METRICS_DOMAIN
          value: galasa.dev/ecosystem
        - name: KUBERNETES_MIN_VERSION
          value: 1.17.13
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          # User 65532 is the distroless nonroot user ID
          runAsUser: 65532
          runAsGroup: 65532